menu:
    Blog: /
    Archive: /archives/
    Instagram: https://www.instagram.com/haigeeek/
    GitHub: https://github.com/haigeek
    About: /about
	
favicon: space-satellite-dish.png
logo: space-satellite-dish.png

# Comment
# e.g disqus: seansun
disqus: https-haigeek-cn
duoshuo:

# Analytics
# google-analytics:
ga: 
# Copyright Infomation
startyear: 2016
